# Install NeoVim 
# ARG INSTALL_NEOVIM="true"
COPY custom-scripts/neovim/* /tmp/library-scripts/
RUN bash /tmp/library-scripts/install-neovim.sh "${USERNAME}" \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts/