# Configure bash
COPY custom-scripts/bash/* \
    /tmp/library-scripts/
RUN bash /tmp/library-scripts/update-bash.sh "${USERNAME}" \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts